---
title: "Atlas de Poliquetas"
subtitle: "Bacia de Pelotas — Margem Continental Sul do Brasil"
format:
  html:
    theme:
      - flatly
      - custom.scss
    include-in-header:
      - text: |
          <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&family=Merriweather:wght@700&display=swap" rel="stylesheet">
---

::: {.callout-note appearance="simple" icon=false}
🪱 **[Acessar lista completa de espécies](lista_especies.html)**

📄 **[Baixar PDF do checklist](lista_especies.pdf)**
:::



::: {.justify} 
A classe **Polychaeta** (Annelida) constitui um dos grupos de invertebrados marinhos mais diversos do ambiente bentônico costeiro e oceânico, estando associados a distintos tipos de substratos. Estão presentes desde a zona entre marés até maiores profundidades. Do ponto de vista ecológico, os poliquetas desempenham papéis centrais como bioturbadores (ciclo biogeoquímico), consumidores (detritos, algas e partículas em suspensão), presas (de peixes e crustáceos) e indicadores ambientais, sendo sensíveis a perturbações ambientais.

O presente levantamento taxonômico foi restrito aos registros de Polychaeta presentes na Bacia de Pelotas, localizada na margem continental sul do Brasil, desde o sul da Ilha de Santa Catarina (limite com a Bacia de Santos) até a fronteira do Brasil com o Uruguai. Apesar da relevância ecológica e taxonômica para a região, o conhecimento sobre a fauna de poliquetas da Bacia de Pelotas permanece fragmentado, sem a devida sistematização que permita acesso compilado e atualizado às espécies registradas. *Checklists* de referência estão disponíveis nos estados do sudeste, Paraná e Santa Catarina, evidenciando a importância desse tipo de compilação que serviram de modelo para o presente trabalho. 

 A avaliação de impactos e o monitoramento da qualidade ambiental com base em organismos bênticos dependem não apenas do conhecimento de ocorrência e distribuição das espécies, mas também da resolução taxonômica adequada. No entanto, as informações taxonômicas disponíveis são pouco acessíveis a pessoas sem formação especializada, o que torna os estudos taxonômicos mais restritos. O presente Atlas de Poliquetas da Bacia de Pelotas tem como objetivo reunir, de forma organizada e acessível, o conhecimento taxonômico acumulado sobre os poliquetas registrados nessa região, garantindo o acesso à informação para pesquisadores, professores e profissionais que atuem em biologia marinha e ecologia bentônica. Para isso, o trabalho reúne [listagem de famílias, espécies, ilustrações de referência].
 
 Espera-se que este atlas sirva de base para futuros estudos de monitoramento e avaliação de impactos na região. Além disso,este trabalho integra e fortalece o conjunto de *checklists* já disponíveis para o litoral brasileiro, estimulando iniciativas semelhantes para outras regiões ainda pouco documentadas. 
:::